Market Basket Analysis

Association Analysis

Get our pandas and MLxtend code imported and read the data:

In [1]:
#imports
import pandas as pd #Python data analysis library
import numpy as np #Python scientific computing
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

Citation - “The Instacart Online Grocery Shopping Dataset 2017”, Accessed from https://www.instacart.com/datasets/grocery-shopping-2017"

In [2]:
#import dataset
trainDf = pd.read_csv("../data/raw/order_products__train.csv")
orderDf = pd.read_csv("../data/raw/orders.csv")
productDf = pd.read_csv("../data/raw/products.csv")

We will merge the prior and train dataset to get the complete order dataset. We will use append() for doing so.

In [3]:
priorDf = pd.read_csv("../data/raw/order_products__prior.csv")
trainDf = trainDf.append(priorDf,ignore_index = True)

For counting each product, we can assign reordered column as 1

In [4]:
trainDf['reordered'] = 1

In [5]:
productCountDf = trainDf.groupby("product_id",as_index = False)["order_id"].count()

In [6]:
newproductCountDf=productCountDf.merge(productDf, left_on='product_id', right_on='product_id', how='inner')
newDf = newproductCountDf[['product_id','product_name']]
newDf

       product_id                                       product_name
0               1                         Chocolate Sandwich Cookies
1               2                                   All-Seasons Salt
2               3               Robust Golden Unsweetened Oolong Tea
3               4  Smart Ones Classic Favorites Mini Rigatoni Wit...
4               5                          Green Chile Anytime Sauce
5               6                                       Dry Nose Oil
6               7                     Pure Coconut Water With Orange
7               8                  Cut Russet Potatoes Steam N' Mash
8               9                  Light Strawberry Blueberry Yogurt
9              10     Sparkling Orange Juice & Prickly Pear Beverage
10             11                                  Peach Mango Juice
11             12                         Chocolate Fudge Layer Cake
12             13                                  Saline Nasal Mist
13             14                     Fresh Scent Dishwasher Cleaner
14             15                           Overnight Diapers Size 6
15             16                      Mint Chocolate Flavored Syrup
16             17                                  Rendered Duck Fat
17             18                Pizza for One Suprema  Frozen Pizza
18             19   Gluten Free Quinoa Three Cheese & Mushroom Blend
19             20     Pomegranate Cranberry & Aloe Vera Enrich Drink
20             21                   Small & Medium Dental Dog Treats
21             22                  Fresh Breath Oral Rinse Mild Mint
22             23                             Organic Turkey Burgers
23             24  Tri-Vi-Sol® Vitamins A-C-and D Supplement Drop...
24             25            Salted Caramel Lean Protein & Fiber Bar
25             26        Fancy Feast Trout Feast Flaked Wet Cat Food
26             27  Complete Spring Water Foaming Antibacterial Ha...
27             28                                  Wheat Chex Cereal
28             29  Fresh Cut Golden Sweet No Salt Added Whole Ker...
29             30         Three Cheese Ziti, Marinara with Meatballs
...           ...                                                ...
49655       49659                            Organic Creamed Coconut
49656       49660                        Professionals Sleek Shampoo
49657       49661                                              Porto
49658       49662                       Bacon Cheddar Pretzel Pieces
49659       49663  Ultra Protein Power Crunch Peanut Butter N' Ho...
49660       49664                     Lemon Cayenne Drinking Vinegar
49661       49665      Super Dark Coconut Ash & Banana Chocolate Bar
49662       49666                      Ginger Snaps Snacking Cookies
49663       49667           Enchilada with Spanish Rice & Beans Meal
49664       49668                     Apple Cinnamon Scented Candles
49665       49669                                   K Cup Dark Blend
49666       49670                                Beef Summer Sausage
49667       49671                               Milk Chocolate Drops
49668       49672                             Cafe Mocha K-Cup Packs
49669       49673              Stone Baked Multi Grain Artisan Rolls
49670       49674            Frozen Greek Yogurt Bars Chocolate Chip
49671       49675                Cinnamon Dolce Keurig Brewed K Cups
49672       49676                             Ultra Red Energy Drink
49673       49677                    Thick & Chunky Sloppy Joe Sauce
49674       49678                    Large Chicken & Cheese Taquitos
49675       49679                            Famous Chocolate Wafers
49676       49680                 All Natural Creamy Caesar Dressing
49677       49681            Spaghetti with Meatballs and Sauce Meal
49678       49682                                 California Limeade
49679       49683                                     Cucumber Kirby
49680       49684          Vodka, Triple Distilled, Twist of Vanilla
49681       49685                 En Croute Roast Hazelnut Cranberry
49682       49686                                   Artisan Baguette
49683       49687         Smartblend Healthy Metabolism Dry Cat Food
49684       49688                             Fresh Foaming Cleanser

[49685 rows x 2 columns]

In [7]:
#Top 100 most frequently purchased products
topLev = 100
productCountDf = productCountDf.sort_values("order_id",ascending = False)
topProdFrame = productCountDf.iloc[0:topLev,:]
productId= topProdFrame.loc[:,["product_id"]]

Now we will filter the orders and get orders containting the the most frequently purchased products

In [8]:
df = trainDf[0:0]
for i in range(0,99):
    pId = productId.iloc[i]['product_id'] 
    stDf = trainDf[trainDf.product_id == pId ]
    df = df.append(stDf,ignore_index = False)

In [9]:
df.head()

     order_id  product_id  add_to_cart_order  reordered
115       226       24852                  2          1
156       473       24852                  2          1
196       878       24852                  2          1
272      1042       24852                  1          1
297      1139       24852                  1          1

Now we need to consolidate the items into 1 transaction per row with each product 1 hot encoded. Each row will represent an order and each column will represent product_id. If the cell value is '1' say (i,j) then ith order contains jth product.

In [10]:
df=df.merge(newDf, left_on='product_id', right_on='product_id', how='inner')
df=df[['order_id','add_to_cart_order','reordered','product_name']]
df

         order_id  add_to_cart_order  reordered              product_name
0             226                  2          1                    Banana
1             473                  2          1                    Banana
2             878                  2          1                    Banana
3            1042                  1          1                    Banana
4            1139                  1          1                    Banana
5            1145                  1          1                    Banana
6            1468                  1          1                    Banana
7            1572                  3          1                    Banana
8            1591                 19          1                    Banana
9            2068                  1          1                    Banana
10           2415                  2          1                    Banana
11           2937                  1          1                    Banana
12           3056                  9          1                    Banana
13           3209                  2          1                    Banana
14           3243                  4          1                    Banana
15           3378                  9          1                    Banana
16           3740                  6          1                    Banana
17           3898                  3          1                    Banana
18           3957                  8          1                    Banana
19           4164                 13          1                    Banana
20           4284                  3          1                    Banana
21           4340                  1          1                    Banana
22           4431                  1          1                    Banana
23           4556                  1          1                    Banana
24           4562                  2          1                    Banana
25           4827                  2          1                    Banana
26           4918                  1          1                    Banana
27           4968                 13          1                    Banana
28           5447                 17          1                    Banana
29           5739                  4          1                    Banana
...           ...                ...        ...                       ...
7761230   3417348                  9          1  Organic Broccoli Florets
7761231   3417358                  1          1  Organic Broccoli Florets
7761232   3418009                 15          1  Organic Broccoli Florets
7761233   3418216                 30          1  Organic Broccoli Florets
7761234   3418250                 14          1  Organic Broccoli Florets
7761235   3418265                 15          1  Organic Broccoli Florets
7761236   3418483                 25          1  Organic Broccoli Florets
7761237   3418488                  3          1  Organic Broccoli Florets
7761238   3418602                  4          1  Organic Broccoli Florets
7761239   3418640                 14          1  Organic Broccoli Florets
7761240   3418695                  2          1  Organic Broccoli Florets
7761241   3418741                  3          1  Organic Broccoli Florets
7761242   3418781                  5          1  Organic Broccoli Florets
7761243   3418795                  6          1  Organic Broccoli Florets
7761244   3418840                  5          1  Organic Broccoli Florets
7761245   3419159                 16          1  Organic Broccoli Florets
7761246   3419417                  5          1  Organic Broccoli Florets
7761247   3419440                 15          1  Organic Broccoli Florets
7761248   3419547                 12          1  Organic Broccoli Florets
7761249   3419857                  3          1  Organic Broccoli Florets
7761250   3419873                  3          1  Organic Broccoli Florets
7761251   3419980                  2          1  Organic Broccoli Florets
7761252   3420043                  1          1  Organic Broccoli Florets
7761253   3420142                 16          1  Organic Broccoli Florets
7761254   3420310                 10          1  Organic Broccoli Florets
7761255   3420522                  1          1  Organic Broccoli Florets
7761256   3420704                  5          1  Organic Broccoli Florets
7761257   3420826                  4          1  Organic Broccoli Florets
7761258   3420932                 15          1  Organic Broccoli Florets
7761259   3421011                  3          1  Organic Broccoli Florets

[7761260 rows x 4 columns]

In [11]:
basket = df.groupby(['order_id', 'product_name'])['reordered'].sum().unstack().reset_index().fillna(0).set_index('order_id')

In [12]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [13]:
basket_sets = basket.applymap(encode_units)

In [14]:
basket_sets.head()

product_name,100% Raw Coconut Water,100% Whole Wheat Bread,2% Reduced Fat Milk,Apple Honeycrisp Organic,Asparagus,Bag of Organic Bananas,Banana,Bartlett Pears,Blueberries,Boneless Skinless Chicken Breasts,...,Sparkling Natural Mineral Water,Sparkling Water Grapefruit,Spring Water,Strawberries,Uncured Genoa Salami,Unsalted Butter,Unsweetened Almondmilk,Unsweetened Original Almond Breeze Almond Milk,Whole Milk,Yellow Onions
order_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
basket_sets.size

241667217

Now that the data is structured properly, we can generate frequent item sets that have a support of at least 1%

In [16]:
# Build up the frequent items
frequent_itemsets = apriori(basket_sets, min_support=0.01, use_colnames=True)

In [17]:
frequent_itemsets

      support                                        itemsets
0    0.016088                        [100% Raw Coconut Water]
1    0.025855                        [100% Whole Wheat Bread]
2    0.015825                           [2% Reduced Fat Milk]
3    0.035751                      [Apple Honeycrisp Organic]
4    0.029147                                     [Asparagus]
5    0.161785                        [Bag of Organic Bananas]
6    0.201259                                        [Banana]
7    0.015002                                [Bartlett Pears]
8    0.023870                                   [Blueberries]
9    0.021453             [Boneless Skinless Chicken Breasts]
10   0.018425                                [Broccoli Crown]
11   0.019438                              [Bunched Cilantro]
12   0.030820                                       [Carrots]
13   0.016920                              [Clementines, Bag]
14   0.040854                                [Cucumber Kirby]
15   0.021434                        [Extra Virgin Olive Oil]
16   0.030411                             [Fresh Cauliflower]
17   0.015787                                        [Garlic]
18   0.015389                           [Granny Smith Apples]
19   0.016590                    [Grape White/Green Seedless]
20   0.019226                               [Grated Parmesan]
21   0.023762                             [Green Bell Pepper]
22   0.029348                                   [Half & Half]
23   0.021506                                 [Hass Avocados]
24   0.034132                              [Honeycrisp Apple]
25   0.018213                              [Jalapeno Peppers]
26   0.017318                           [Large Alfresco Eggs]
27   0.065869                                   [Large Lemon]
28   0.019873                          [Lime Sparkling Water]
29   0.060080                                         [Limes]
..        ...                                             ...
98   0.031514                                 [Yellow Onions]
99   0.021551  [Bag of Organic Bananas, Organic Baby Spinach]
100  0.026530  [Bag of Organic Bananas, Organic Hass Avocado]
101  0.017321   [Bag of Organic Bananas, Organic Raspberries]
102  0.026505  [Bag of Organic Bananas, Organic Strawberries]
103  0.011306    [Bag of Organic Bananas, Organic Whole Milk]
104  0.010476  [Bag of Organic Bananas, Organic Yellow Onion]
105  0.013453                        [Banana, Cucumber Kirby]
106  0.012142                      [Banana, Honeycrisp Apple]
107  0.017631                           [Banana, Large Lemon]
108  0.013561                                 [Banana, Limes]
109  0.022781                       [Banana, Organic Avocado]
110  0.021873                  [Banana, Organic Baby Spinach]
111  0.014401                    [Banana, Organic Fuji Apple]
112  0.013178                  [Banana, Organic Hass Avocado]
113  0.023895                  [Banana, Organic Strawberries]
114  0.013390                    [Banana, Organic Whole Milk]
115  0.010551                   [Banana, Seedless Red Grapes]
116  0.017689                          [Banana, Strawberries]
117  0.011879                            [Large Lemon, Limes]
118  0.010555                  [Large Lemon, Organic Avocado]
119  0.013228         [Organic Avocado, Organic Baby Spinach]
120  0.010271         [Organic Avocado, Organic Strawberries]
121  0.014810    [Organic Baby Spinach, Organic Hass Avocado]
122  0.016293    [Organic Baby Spinach, Organic Strawberries]
123  0.010252     [Organic Blueberries, Organic Strawberries]
124  0.010984     [Organic Hass Avocado, Organic Raspberries]
125  0.017342    [Organic Hass Avocado, Organic Strawberries]
126  0.014556     [Organic Raspberries, Organic Strawberries]
127  0.010146      [Organic Strawberries, Organic Whole Milk]

[128 rows x 2 columns]

The final step is to generate the rules with their corresponding support, confidence and lift:

In [18]:
# Create the rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules=rules[['antecedants','consequents','antecedent support','consequent support','support','confidence','lift']]

We can also see several where the confidence is high as well.or instance, we can see that there are quite a few rules with a high lift value which means that it occurs more frequently than would be expected given the number of transaction and product combinations.
We can filter the dataframe using standard pandas code. In this case, look for a large lift (2) and high confidence (.1):

In [19]:
rules=rules[ (rules['lift'] >= 2) &
       (rules['confidence'] >= 0.1) ]
rules

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift
6,(Limes),(Large Lemon),0.060080,0.065869,0.011879,0.197723,3.001750
7,(Large Lemon),(Limes),0.065869,0.060080,0.011879,0.180345,3.001750
12,(Organic Blueberries),(Organic Strawberries),0.043024,0.112891,0.010252,0.238274,2.110653
16,(Organic Raspberries),(Organic Hass Avocado),0.058418,0.090483,0.010984,0.188018,2.077938
17,(Organic Hass Avocado),(Organic Raspberries),0.090483,0.058418,0.010984,0.121389,2.077938
22,(Organic Raspberries),(Organic Strawberries),0.058418,0.112891,0.014556,0.249174,2.207206
23,(Organic Strawberries),(Organic Raspberries),0.112891,0.058418,0.014556,0.128940,2.207206
54,(Organic Avocado),(Large Lemon),0.075468,0.065869,0.010555,0.139862,2.123337
55,(Large Lemon),(Organic Avocado),0.065869,0.075468,0.010555,0.160244,2.123337